version: '3.9'

services:
  db:
    image: postgres
    container_name: database
    ports:
      - "5442:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: autoservice
      POSTGRES_USER: autoservice
      POSTGRES_DB: autoservice
      TZ: Europe/Samara
      PGTZ: Europe/Samara
    networks:
      - autoservice-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - autoservice-network

networks:
  autoservice-network:
    driver: bridge